### ISSUE TITLE
There are many references to 'singer' in the code/docs, which should be 'signer'.

### ISSUE THREAD

**Issue by grempe** [Lobstrco/Vault-iOS#1]
The word 'signer' is misspelled in a number of locations in the code and the docs. Seeing as how this application is all about 'signing' this is probably important to fix. I originally found this in section 2 of the in app help docs, but a quick search on the repository found many more instances, many in method signatures.

See:

https://github.com/Lobstrco/Vault-iOS/search?q=singer&unscoped_q=singer

Cheers.

**Comment by gpg4** [comment]
@grempe Glenn, thanks for pointing this out -- it has been fixed
